# Generated by Django 5.0.2 on 2024-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haulistic', '0002_auto_20240216_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_pk', models.PositiveIntegerField(default=0)),
                ('element_name', models.CharField(max_length=32)),
                ('element_description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='To_Do_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=32)),
                ('list_category', models.CharField(blank=True, max_length=32)),
                ('list_owner', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shopping_list',
            name='list_elements',
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='list_owner',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
