# Generated by Django 5.0.2 on 2024-02-17 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haulistic', '0004_auto_20240217_1736'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_element',
            name='list_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haulistic.shopping_list'),
        ),
        migrations.AlterField(
            model_name='shopping_list',
            name='list_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='to_do_element',
            name='list_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haulistic.to_do_list'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='list_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
